# Generated by Django 5.0 on 2023-12-31 05:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToDo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Date', models.DateTimeField(default=datetime.datetime(2023, 12, 31, 11, 22, 16, 703272))),
                ('Discreption', models.TextField(null=True)),
            ],
        ),
    ]
